language: php

cache:
  directories:
        - $HOME/.composer/cache

php:
  - '5.6'
  - '7.3'
  - '7.4'

before_install:
  - composer global require hirak/prestissimo

install:
  - composer install
  - composer require giggsey/libphonenumber-for-php

script:
  - php vendor/bin/phpunit

after_success:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover tests/_reports/logs/clover.xml

branches:
  only: 
    - master